'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, CalendarDays, ChevronDown, Clock3, MapPin, Menu, Minus, Mic, Phone, Plus, ShoppingBag, Star, X } from 'lucide-react'
import { AuthHeader } from '@/components/auth-header'

type MenuItem = { category: string; icon: string; name: string; price: number; description: string; image: string; pizza?: boolean }
type CartItem = MenuItem & { quantity: number; size?: string }

const menu: MenuItem[] = [
  { category: 'Burgers', icon: '01', name: 'The Classic', price: 650, description: 'Double smashed beef, American cheese, pickles, crisp onion, house sauce.', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85' },
  { category: 'Burgers', icon: '02', name: 'Firebird', price: 750, description: 'Crispy hot chicken, jalapeño slaw, honey heat, toasted brioche.', image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=900&q=85' },
  { category: 'Pizza', icon: '03', name: 'Pepperoni', price: 650, description: 'Charred crust, mozzarella, pepperoni, and a little chili oil.', image: 'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=900&q=85', pizza: true },
  { category: 'Pizza', icon: '04', name: 'Cheese Burst', price: 600, description: 'Tomato sauce, mozzarella, cheddar, and a golden cheese-filled crust.', image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=85', pizza: true },
  { category: 'Pizza', icon: '05', name: 'Chicken Tikka', price: 700, description: 'Spiced chicken tikka, onions, peppers, mozzarella, and herb sauce.', image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=85', pizza: true },
  { category: 'Pizza', icon: '06', name: 'Malai Boti', price: 750, description: 'Creamy malai boti, onions, jalapeños, mozzarella, and smoky seasoning.', image: 'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=900&q=85', pizza: true },
  { category: 'Nuggets', icon: '07', name: 'Chicken Nuggets', price: 300, description: 'Crispy bite-sized chicken nuggets served with your choice of dip.', image: 'https://images.unsplash.com/photo-1562967916-eb82221dfb92?auto=format&fit=crop&w=900&q=85' },
  { category: 'Nuggets', icon: '08', name: 'Golden Tenders', price: 400, description: 'Crunchy chicken tenders with a creamy ranch dip.', image: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?auto=format&fit=crop&w=900&q=85' },
  { category: 'Sides', icon: '09', name: 'Classic Fries', price: 200, description: 'Crispy golden fries with house seasoning.', image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85' },
  { category: 'Sides', icon: '10', name: 'Mozzarella Sticks', price: 350, description: 'Crispy potato sticks filled with molten mozzarella, served with marinara dip.', image: '/images/mozzarella-potato-sticks.png' },
  { category: 'Sandwiches', icon: '11', name: 'Crispy Chicken Sandwich', price: 450, description: 'Crunchy chicken, lettuce, cheese, and garlic mayo.', image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=900&q=85' },
  { category: 'Drinks', icon: '12', name: 'Fresh Lemonade', price: 150, description: 'Bright, chilled lemonade made fresh with a citrusy finish.', image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=85' },
  { category: 'Combos / Deals', icon: '13', name: 'Lunch Break Combo', price: 900, description: 'Crispy chicken sandwich, fries, and a chilled soft drink.', image: 'https://images.unsplash.com/photo-1550507992-eb63ffee0847?auto=format&fit=crop&w=900&q=85' },
]

const categories = ['All', ...Array.from(new Set(menu.map((item) => item.category)))]
const sizes = [{ label: 'Small', price: 650 }, { label: 'Medium', price: 1000 }, { label: 'Large', price: 1700 }]
const money = (value: number) => `PKR ${value.toLocaleString('en-PK')}`

const faqs = [
  ['Do you deliver?', 'Yes — we deliver across Bahria Orchard Lahore and nearby areas.'],
  ['What are your hours?', "We're open daily from 11am to midnight."],
  ['How do I place an order?', "Add items to your cart on the menu, then checkout — you'll be redirected to WhatsApp to confirm your order directly with us."],
  ['What payment methods do you accept?', 'Currently cash on delivery / pay at pickup. Online payment is coming soon.'],
  ['Can I customize my order?', 'Yes, use the notes field at checkout to mention any changes (e.g. no sauce, extra cheese).'],
  ['Is there a minimum order for delivery?', 'No minimum order right now.'],
]

// Placeholder testimonials — swap these for verified customer feedback later.
const testimonials = [
  ['The Firebird burger is unreal — crispy, spicy, and always fresh. Cravings is my go-to now.', 'Ayesha K.', 'Regular customer'],
  ['Ordered through WhatsApp and it was so easy. Food showed up hot and on time.', 'Bilal S.', 'Delivery customer'],
  ['Best smash burger in Bahria Orchard, hands down. The Cheese Burst pizza is also insane.', 'Zara M.', 'Regular customer'],
]

export function RestaurantSite() {
  const [activeCategory, setActiveCategory] = useState('All')
  const [cart, setCart] = useState<CartItem[]>([])
  const [selectedItem, setSelectedItem] = useState<MenuItem | null>(null)
  const [selectedSize, setSelectedSize] = useState(sizes[1])
  const [detailQuantity, setDetailQuantity] = useState(1)
  const [cartOpen, setCartOpen] = useState(false)
  const [checkoutOpen, setCheckoutOpen] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const [voiceOpen, setVoiceOpen] = useState(false)
  const [reservationSent, setReservationSent] = useState(false)
  const [openFaq, setOpenFaq] = useState<number | null>(0)
  const [activeTestimonial, setActiveTestimonial] = useState(0)
  const filtered = useMemo(() => activeCategory === 'All' ? menu : menu.filter((item) => item.category === activeCategory), [activeCategory])
  const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0)
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)

  const openDetails = (item: MenuItem) => { setSelectedItem(item); setSelectedSize(sizes[1]); setDetailQuantity(1) }
  const addToCart = (item: MenuItem, quantity = 1, size?: string) => setCart((current) => {
    const key = `${item.name}-${size ?? 'regular'}`
    const existing = current.find((entry) => `${entry.name}-${entry.size ?? 'regular'}` === key)
    return existing ? current.map((entry) => `${entry.name}-${entry.size ?? 'regular'}` === key ? { ...entry, quantity: entry.quantity + quantity } : entry) : [...current, { ...item, quantity, size }]
  })
  const updateQuantity = (index: number, delta: number) => setCart((current) => current.flatMap((item, itemIndex) => itemIndex === index ? (item.quantity + delta > 0 ? [{ ...item, quantity: item.quantity + delta }] : []) : [item]))
  const submitOrder = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const formData = new FormData(event.currentTarget)
    const name = String(formData.get('name') ?? '')
    const phone = String(formData.get('phone') ?? '')
    const orderType = String(formData.get('orderType') ?? 'Delivery')
    const address = String(formData.get('address') ?? '')
    const notes = String(formData.get('notes') ?? '')
    const itemsList = cart
      .map(item => `- ${item.quantity}x ${item.name}${item.size ? ` (${item.size})` : ''} — PKR ${item.price * item.quantity}`)
      .join('\n')

    const addressLine = orderType === 'Delivery' ? `*Address:* ${address}\n` : ''
    const notesLine = notes.trim() ? `*Notes:* ${notes.trim()}` : '*Notes:* None'

    const message = `*New Order — Cravings*
*Customer:* ${name}
*Phone:* ${phone}
*Order type:* ${orderType}
${addressLine}
*Items:*
${itemsList}

*Total: PKR ${total}*

${notesLine}`
    const whatsappUrl = `https://wa.me/923217166976?text=${encodeURIComponent(message)}`
    window.open(whatsappUrl, '_blank', 'noopener,noreferrer')
    setCheckoutOpen(false)
    setCartOpen(false)
  }

  return <div className="min-h-screen bg-[#f5f1e9] text-[#1e1f1c] selection:bg-[#ff5a36] selection:text-white">
    <header className="fixed inset-x-0 top-0 z-40 border-b border-white/10 bg-[#1e1f1c]/95 text-white backdrop-blur-md"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-10"><a href="#home" className="flex items-center gap-3" aria-label="Cravings home"><span className="grid size-10 place-items-center rounded-full bg-[#ff5a36] text-lg font-black italic">R</span><span className="font-black uppercase tracking-[-0.08em] text-xl">CRAVINGS<span className="text-[#ff5a36]">.</span></span></a><nav className="hidden items-center gap-8 text-xs font-bold uppercase tracking-[0.16em] text-white/70 md:flex"><a href="#menu">Menu</a><a href="#story">Our story</a><a href="#visit">Visit us</a></nav><div className="flex items-center gap-2"><button onClick={() => setCartOpen(true)} className="relative flex items-center gap-2 rounded-full bg-[#ffb627] px-4 py-2.5 text-xs font-black uppercase tracking-wider text-[#1e1f1c]"><ShoppingBag className="size-4" /><span className="hidden sm:inline">Order</span>{totalItems > 0 && <span className="grid size-5 place-items-center rounded-full bg-[#1e1f1c] text-[10px] text-white">{totalItems}</span>}</button><AuthHeader /><button className="p-2 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation"><Menu /></button></div></div>{menuOpen && <nav className="flex flex-col gap-5 border-t border-white/10 bg-[#1e1f1c] px-5 py-5 text-xs font-bold uppercase tracking-[0.16em] md:hidden"><a href="#menu">Menu</a><a href="#story">Our story</a><a href="#visit">Visit us</a></nav>}</header>
    <main><section id="home" className="bg-[#1e1f1c] px-5 pb-20 pt-40 text-white lg:px-10"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-2"><div><p className="mb-6 text-xs font-black uppercase tracking-[0.28em] text-[#ffb627]">Independent since 2018</p><h1 className="text-[clamp(4rem,9vw,8.5rem)] font-black uppercase leading-[.82] tracking-[-0.09em]">Good food.<br /><span className="text-[#ff5a36]">Bad</span> attitude.</h1><p className="mt-8 max-w-md text-lg leading-relaxed text-white/65">Big flavor, zero fuss. Smash burgers, hot chicken, and a little bit of chaos — made fresh in the heart of the city.</p><a href="#menu" className="mt-10 inline-flex items-center gap-3 rounded-full bg-[#ff5a36] px-7 py-4 text-sm font-black uppercase tracking-wider">See the menu <ArrowRight className="size-4" /></a></div><img src="https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?auto=format&fit=crop&w=1100&q=90" alt="Juicy double cheeseburger with fries" className="aspect-square w-full rounded-[2rem] border-8 border-white/10 object-cover shadow-2xl lg:rotate-3" /></div></section>
    <section id="menu" className="mx-auto max-w-7xl scroll-mt-20 px-5 py-24 lg:px-10"><p className="mb-3 text-xs font-black uppercase tracking-[0.25em] text-[#ff5a36]">What&apos;s cooking</p><h2 className="text-5xl font-black uppercase leading-none tracking-[-0.07em] md:text-7xl">The good<br /><span className="text-[#ff5a36]">stuff.</span></h2><div className="mt-10 flex gap-2 overflow-x-auto pb-2">{categories.map((category) => <button key={category} onClick={() => setActiveCategory(category)} className={`whitespace-nowrap rounded-full border px-4 py-2 text-xs font-black uppercase tracking-wider ${activeCategory === category ? 'border-[#1e1f1c] bg-[#1e1f1c] text-white' : 'border-black/15'}`}>{category}</button>)}</div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{filtered.map((item) => <article key={item.name} className="group cursor-pointer overflow-hidden rounded-[1.4rem] bg-white shadow-sm transition-all hover:-translate-y-1 hover:shadow-xl" onClick={() => openDetails(item)}><div className="relative overflow-hidden"><img src={item.image} alt={item.name} className="aspect-[1.6] w-full object-cover transition-transform duration-500 group-hover:scale-105" /><span className="absolute left-3 top-3 rounded-full bg-[#ffb627] px-2.5 py-1 text-[10px] font-black">{item.icon}</span></div><div className="p-4"><div className="flex items-start justify-between gap-3"><h3 className="font-black uppercase leading-tight">{item.name}</h3><span className="shrink-0 text-sm font-black text-[#ff5a36]">{money(item.price)}</span></div><p className="mt-2 text-sm leading-relaxed text-black/55">{item.description}</p><div className="mt-4 grid grid-cols-2 gap-2" onClick={(event) => event.stopPropagation()}><button onClick={() => addToCart(item, 1, item.pizza ? 'Medium' : undefined)} className="rounded-full border border-[#1e1f1c]/15 px-3 py-2 text-[10px] font-black uppercase tracking-wider">Add to cart</button><button onClick={() => { addToCart(item, 1, item.pizza ? 'Medium' : undefined); setCartOpen(true) }} className="rounded-full bg-[#ff5a36] px-3 py-2 text-[10px] font-black uppercase tracking-wider text-white">Order now</button></div></div></article>)}</div></section>
    <section id="story" className="scroll-mt-20 bg-[#ff5a36] px-5 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><p className="mb-4 text-xs font-black uppercase tracking-[0.25em]">Not your average</p><h2 className="max-w-xl text-5xl font-black uppercase leading-[.9] tracking-[-0.07em] md:text-7xl">We make fast food <span className="text-white">feel slow.</span></h2><p className="mt-8 max-w-lg text-lg leading-relaxed text-[#1e1f1c]/70">Fresh ingredients, loud flavors, and no shortcuts. Come hungry.</p></div></section>
    <section id="testimonials" className="relative scroll-mt-20 overflow-hidden bg-[#1e1f1c] px-5 py-24 text-white lg:px-10"><div className="pointer-events-none absolute -right-20 top-0 size-[32rem] rounded-full bg-[#ffb627]/20 blur-3xl" /><div className="pointer-events-none absolute right-0 top-0 h-full w-1/2 opacity-30" style={{ background: 'repeating-conic-gradient(from 220deg at 100% 0%, transparent 0deg 8deg, #ff8a18 9deg 10deg, transparent 11deg 18deg)' }} /><div className="relative mx-auto max-w-5xl text-center"><span className="rounded-full border border-[#ffb627]/60 px-4 py-2 text-[10px] font-black tracking-[0.25em] text-[#ffb627]">TESTIMONIALS</span><h2 className="mt-8 text-5xl font-black uppercase leading-[.88] tracking-[-0.07em] md:text-7xl">Loved by hungry regulars.</h2><p className="mx-auto mt-5 max-w-lg text-white/60">Real feedback from real customers who keep coming back for more.</p><div className="mx-auto mt-12 flex max-w-3xl items-center gap-3 md:gap-8"><button onClick={() => setActiveTestimonial((activeTestimonial - 1 + testimonials.length) % testimonials.length)} className="grid size-11 shrink-0 place-items-center rounded-full border border-white/20 text-[#ffb627] transition hover:bg-[#ffb627] hover:text-[#1e1f1c]" aria-label="Previous testimonial"><ArrowLeft className="size-4" /></button><div className="relative min-h-[260px] flex-1"><div className="absolute inset-x-4 top-4 h-full rotate-3 rounded-[2rem] bg-[#ff5a36]/60" /><article className="relative flex min-h-[260px] flex-col justify-between rounded-[2rem] bg-[#30312d] p-7 text-left shadow-2xl md:p-10"><p className="text-xl font-bold leading-relaxed md:text-3xl">&ldquo;{testimonials[activeTestimonial][0]}&rdquo;</p><div className="mt-8 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#ff5a36] text-sm font-black">{testimonials[activeTestimonial][1][0]}</span><span><strong className="block text-sm">{testimonials[activeTestimonial][1]}</strong><small className="text-white/50">{testimonials[activeTestimonial][2]}</small></span></div></article></div><button onClick={() => setActiveTestimonial((activeTestimonial + 1) % testimonials.length)} className="grid size-11 shrink-0 place-items-center rounded-full border border-white/20 text-[#ffb627] transition hover:bg-[#ffb627] hover:text-[#1e1f1c]" aria-label="Next testimonial"><ArrowRight className="size-4" /></button></div></div></section>
    <section id="faq" className="relative scroll-mt-20 overflow-hidden bg-black px-5 py-24 text-white lg:px-10"><div className="pointer-events-none absolute -left-8 top-8 select-none text-[20rem] font-black leading-none text-white/[0.035]">FQ</div><div className="relative mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="mb-4 text-xs font-black uppercase tracking-[0.25em] text-[#ffb627]">FAQ</p><h2 className="text-5xl font-black uppercase leading-[.88] tracking-[-0.07em] md:text-7xl">Got<br />questions?</h2></div><div className="max-w-md pb-2 text-lg leading-relaxed text-white/60"><p>Everything you need to know before you order.</p><p className="mt-4 text-sm text-white/40">Still curious? Drop us a message and we&apos;ll get you sorted.</p></div></div><div className="mt-12 grid gap-3">{faqs.map(([question, answer], index) => <div key={question} className="rounded-2xl bg-[#1e1f1c] px-5"><button className="flex w-full items-center justify-between gap-4 py-5 text-left font-black" onClick={() => setOpenFaq(openFaq === index ? null : index)} aria-expanded={openFaq === index}><span>{question}</span><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[#ffb627] text-[#1e1f1c]">{openFaq === index ? <Minus className="size-4" /> : <Plus className="size-4" />}</span></button><div className={`grid transition-[grid-template-rows] duration-300 ${openFaq === index ? 'grid-rows-[1fr]' : 'grid-rows-[0fr]'}`}><p className="min-h-0 overflow-hidden pb-5 pr-10 text-sm leading-relaxed text-white/55">{answer}</p></div></div>)}</div></div></section>
    <section id="visit" className="scroll-mt-20 px-5 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><p className="mb-3 text-xs font-black uppercase tracking-[0.25em] text-[#ff5a36]">Come through</p><h2 className="text-5xl font-black uppercase leading-[.9] tracking-[-0.07em] md:text-7xl">Pull up.<br /><span className="text-[#ff5a36]">We&apos;re open.</span></h2><div className="mt-10 flex flex-wrap gap-8 text-sm"><span className="flex gap-2"><MapPin className="size-5 text-[#ff5a36]" /> Bahria Orchard Lahore</span><span className="flex gap-2"><Clock3 className="size-5 text-[#ff5a36]" /> 11am–midnight</span><span className="flex gap-2"><Phone className="size-5 text-[#ff5a36]" /> (718) 555-RIOT</span></div></div></section></main><footer className="bg-[#1e1f1c] px-5 py-12 text-white"><div className="mx-auto max-w-7xl font-black uppercase">CRAVINGS<span className="text-[#ff5a36]">.</span></div></footer>

    {selectedItem && <div className="fixed inset-0 z-50 grid place-items-center p-5"><button aria-label="Close item details" className="absolute inset-0 bg-black/60" onClick={() => setSelectedItem(null)} /><section role="dialog" aria-modal="true" aria-labelledby="item-title" className="relative max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-[2rem] bg-[#f5f1e9] shadow-2xl"><button onClick={() => setSelectedItem(null)} className="absolute right-4 top-4 rounded-full bg-white/90 p-2" aria-label="Close item details"><X /></button><img src={selectedItem.image} alt={selectedItem.name} className="aspect-[1.8] w-full object-cover" /><div className="p-6 md:p-8"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#ff5a36]">{selectedItem.category}</p><h2 id="item-title" className="mt-2 text-4xl font-black uppercase leading-none">{selectedItem.name}</h2><p className="mt-4 leading-relaxed text-black/60">{selectedItem.description}</p>{selectedItem.pizza && <div className="mt-6"><p className="mb-2 text-xs font-black uppercase tracking-wider">Choose your size</p><div className="grid grid-cols-3 gap-2">{sizes.map((size) => <button key={size.label} onClick={() => setSelectedSize(size)} className={`rounded-xl border p-3 text-left ${selectedSize.label === size.label ? 'border-[#ff5a36] bg-[#ff5a36] text-white' : 'border-black/10 bg-white'}`}><span className="block text-sm font-black">{size.label}</span><span className="text-xs">{money(size.price)}</span></button>)}</div></div>}<div className="mt-7 flex items-center justify-between gap-4"><div className="flex items-center gap-3 rounded-full bg-white p-2"><button onClick={() => setDetailQuantity(Math.max(1, detailQuantity - 1))} className="grid size-8 place-items-center rounded-full bg-[#f5f1e9]" aria-label="Decrease quantity"><Minus className="size-4" /></button><span className="w-5 text-center font-black">{detailQuantity}</span><button onClick={() => setDetailQuantity(detailQuantity + 1)} className="grid size-8 place-items-center rounded-full bg-[#f5f1e9]" aria-label="Increase quantity"><Plus className="size-4" /></button></div><button onClick={() => { addToCart(selectedItem, detailQuantity, selectedItem.pizza ? selectedSize.label : undefined); setSelectedItem(null) }} className="flex-1 rounded-full bg-[#1e1f1c] px-5 py-4 text-sm font-black uppercase tracking-wider text-white">Add to cart · {money((selectedItem.pizza ? selectedSize.price : selectedItem.price) * detailQuantity)}</button></div></div></section></div>}

    {cartOpen && <div className="fixed inset-0 z-50"><button aria-label="Close cart" className="absolute inset-0 bg-black/50" onClick={() => setCartOpen(false)} /><aside className="absolute right-0 top-0 flex h-full w-full max-w-md flex-col bg-[#f5f1e9] p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#ff5a36]">Your order</p><h2 className="mt-1 text-3xl font-black uppercase">The good stuff</h2></div><button onClick={() => setCartOpen(false)} aria-label="Close cart"><X /></button></div>{cart.length === 0 ? <div className="grid flex-1 place-items-center text-center"><div><ShoppingBag className="mx-auto size-12 text-black/20" /><p className="mt-4 font-black uppercase">Your bag is empty</p></div></div> : <><div className="mt-8 flex-1 overflow-y-auto"><div className="grid gap-4">{cart.map((item, index) => <div key={`${item.name}-${item.size}`} className="flex gap-3 rounded-2xl bg-white p-3"><img src={item.image} alt="" className="size-20 rounded-xl object-cover" /><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><div><p className="font-black uppercase leading-tight">{item.name}</p>{item.size && <p className="mt-1 text-xs text-black/50">{item.size}</p>}</div><p className="font-black text-[#ff5a36]">{money(item.price * item.quantity)}</p></div><div className="mt-3 flex items-center gap-2"><button onClick={() => updateQuantity(index, -1)} className="grid size-7 place-items-center rounded-full bg-[#f5f1e9]" aria-label="Decrease item quantity"><Minus className="size-3" /></button><span className="w-4 text-center text-sm font-bold">{item.quantity}</span><button onClick={() => updateQuantity(index, 1)} className="grid size-7 place-items-center rounded-full bg-[#f5f1e9]" aria-label="Increase item quantity"><Plus className="size-3" /></button></div></div></div>)}</div></div><div className="border-t border-black/10 pt-5"><div className="mb-4 flex justify-between text-lg font-black uppercase"><span>Total</span><span className="text-[#ff5a36]">{money(total)}</span></div><button onClick={() => { setCartOpen(false); setCheckoutOpen(true) }} className="w-full rounded-full bg-[#ff5a36] px-5 py-4 text-sm font-black uppercase tracking-wider text-white">Checkout</button></div></>}</aside></div>}

    {checkoutOpen && <div className="fixed inset-0 z-50 grid place-items-center p-5"><button aria-label="Close checkout" className="absolute inset-0 bg-black/60" onClick={() => setCheckoutOpen(false)} /><section role="dialog" aria-modal="true" aria-labelledby="checkout-title" className="relative max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-[2rem] bg-[#f5f1e9] p-6 shadow-2xl md:p-8"><button onClick={() => setCheckoutOpen(false)} className="absolute right-5 top-5" aria-label="Close checkout"><X /></button><p className="text-xs font-black uppercase tracking-[0.2em] text-[#ff5a36]">Almost there</p><h2 id="checkout-title" className="mt-2 text-4xl font-black uppercase">Checkout</h2><form onSubmit={submitOrder} className="mt-7 grid gap-4"><label className="grid gap-2 text-xs font-black uppercase tracking-wider">Customer name<input required name="name" className="rounded-xl border-0 bg-white px-4 py-3 text-sm normal-case outline-none ring-[#ff5a36] focus:ring-2" placeholder="Your name" /></label><label className="grid gap-2 text-xs font-black uppercase tracking-wider">Phone number<input required name="phone" type="tel" className="rounded-xl border-0 bg-white px-4 py-3 text-sm normal-case outline-none focus:ring-2 focus:ring-[#ff5a36]" placeholder="03XX XXXXXXX" /></label><div className="grid gap-2 text-xs font-black uppercase tracking-wider">Order type<div className="grid grid-cols-3 gap-2">{['Dine in', 'Take out', 'Delivery'].map((type) => <label key={type} className="rounded-xl bg-white p-3 text-center text-xs"><input type="radio" name="orderType" value={type} defaultChecked={type === 'Delivery'} className="sr-only peer" /><span className="peer-checked:text-[#ff5a36]">{type}</span></label>)}</div></div><label className="grid gap-2 text-xs font-black uppercase tracking-wider">Delivery address<textarea name="address" required className="min-h-20 rounded-xl border-0 bg-white px-4 py-3 text-sm normal-case outline-none focus:ring-2 focus:ring-[#ff5a36]" placeholder="Address or table number" /></label><label className="grid gap-2 text-xs font-black uppercase tracking-wider">Order notes<textarea name="notes" className="min-h-16 rounded-xl border-0 bg-white px-4 py-3 text-sm normal-case outline-none focus:ring-2 focus:ring-[#ff5a36]" placeholder="Extra sauce? No onions?" /></label><div className="mt-2 rounded-2xl bg-[#1e1f1c] p-5 text-white"><div className="flex justify-between font-black uppercase"><span>Pay at counter / COD</span><span className="text-[#ffb627]">{money(total)}</span></div><button className="mt-5 w-full rounded-full bg-[#ffb627] px-5 py-4 text-sm font-black uppercase tracking-wider text-[#1e1f1c]">Place order</button></div></form></section></div>}

    {voiceOpen && <div className="fixed inset-0 z-50 grid place-items-center p-5"><button aria-label="Close voice agent" className="absolute inset-0 bg-black/60" onClick={() => setVoiceOpen(false)} /><section role="dialog" aria-modal="true" className="relative w-full max-w-md rounded-[2rem] bg-[#1e1f1c] p-8 text-white"><button onClick={() => setVoiceOpen(false)} className="absolute right-5 top-5" aria-label="Close voice agent"><X /></button><Mic className="mx-auto mt-4 size-12 text-[#ffb627]" /><h2 className="mt-6 text-center text-3xl font-black uppercase">Talk food.<br /><span className="text-[#ff5a36]">Skip typing.</span></h2><p className="mt-5 text-center text-sm text-white/60">Voice chat integration coming soon.</p></section></div>}
  </div>
}
